<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260612123000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create custom CMS tables for Bazma showcase site';
    }

    public function up(Schema $schema): void
    {
        if ($this->isPostgreSql()) {
            $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) NOT NULL, slug VARCHAR(170) NOT NULL, title_en VARCHAR(160) DEFAULT NULL, title_ar VARCHAR(160) DEFAULT NULL, event_date DATE DEFAULT NULL, location VARCHAR(255) NOT NULL, category VARCHAR(80) NOT NULL, source_url VARCHAR(255) DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, excerpt VARCHAR(220) DEFAULT NULL, excerpt_en VARCHAR(220) DEFAULT NULL, excerpt_ar VARCHAR(220) DEFAULT NULL, featured BOOLEAN NOT NULL, position INT NOT NULL, description TEXT NOT NULL, description_en TEXT DEFAULT NULL, description_ar TEXT DEFAULT NULL, published BOOLEAN NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_3BAE0AA989D9B62 ON event (slug)');
            $this->addSql('CREATE TABLE gallery_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) NOT NULL, title_en VARCHAR(160) DEFAULT NULL, title_ar VARCHAR(160) DEFAULT NULL, image_url VARCHAR(255) NOT NULL, credit VARCHAR(255) DEFAULT NULL, source_url VARCHAR(255) DEFAULT NULL, featured BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE TABLE page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(120) NOT NULL, title_en VARCHAR(120) DEFAULT NULL, title_ar VARCHAR(120) DEFAULT NULL, slug VARCHAR(140) NOT NULL, summary VARCHAR(180) NOT NULL, summary_en VARCHAR(180) DEFAULT NULL, summary_ar VARCHAR(180) DEFAULT NULL, body TEXT NOT NULL, body_en TEXT DEFAULT NULL, body_ar TEXT DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, published BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_140AB620989D9B62 ON page (slug)');
            $this->addSql('CREATE TABLE site_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting_key VARCHAR(80) NOT NULL, setting_value TEXT NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_57B40A2045D6295E ON site_setting (setting_key)');
            $this->addSql('CREATE TABLE social_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, platform VARCHAR(80) NOT NULL, title VARCHAR(160) NOT NULL, title_en VARCHAR(160) DEFAULT NULL, title_ar VARCHAR(160) DEFAULT NULL, summary TEXT NOT NULL, summary_en TEXT DEFAULT NULL, summary_ar TEXT DEFAULT NULL, url VARCHAR(255) NOT NULL, image_url VARCHAR(255) NOT NULL, category VARCHAR(80) NOT NULL, featured BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE TABLE community_organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, name_en VARCHAR(160) DEFAULT NULL, name_ar VARCHAR(160) DEFAULT NULL, type VARCHAR(80) NOT NULL, description TEXT NOT NULL, description_en TEXT DEFAULT NULL, description_ar TEXT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, image_url VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE TABLE admin_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(120) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON admin_user (email)');
            $this->addSql('CREATE TABLE page_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, page_id INT NOT NULL, title VARCHAR(180) NOT NULL, image_url VARCHAR(255) NOT NULL, caption VARCHAR(255) DEFAULT NULL, position INT NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_E0F3026EC4663E4 ON page_media (page_id)');
            $this->addSql('ALTER TABLE page_media ADD CONSTRAINT FK_E0F3026EC4663E4 FOREIGN KEY (page_id) REFERENCES page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

            return;
        }

        $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(160) NOT NULL, event_date DATE DEFAULT NULL, location VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, published TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_image (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(160) NOT NULL, image_url VARCHAR(255) NOT NULL, credit VARCHAR(255) DEFAULT NULL, source_url VARCHAR(255) DEFAULT NULL, featured TINYINT(1) NOT NULL, position INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, summary VARCHAR(180) NOT NULL, body LONGTEXT NOT NULL, image_url VARCHAR(255) DEFAULT NULL, published TINYINT(1) NOT NULL, position INT NOT NULL, UNIQUE INDEX UNIQ_140AB620989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE site_setting (id INT AUTO_INCREMENT NOT NULL, setting_key VARCHAR(80) NOT NULL, setting_value LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_57B40A2045D6295E (setting_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    public function down(Schema $schema): void
    {
        if ($this->isPostgreSql()) {
            $this->addSql('DROP TABLE page_media');
            $this->addSql('DROP TABLE admin_user');
            $this->addSql('DROP TABLE community_organization');
            $this->addSql('DROP TABLE social_link');
            $this->addSql('DROP TABLE site_setting');
            $this->addSql('DROP TABLE page');
            $this->addSql('DROP TABLE gallery_image');
            $this->addSql('DROP TABLE event');

            return;
        }

        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE gallery_image');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE site_setting');
    }

    private function isPostgreSql(): bool
    {
        return str_contains($this->connection->getDatabasePlatform()::class, 'PostgreSQL');
    }
}
